schema_version = "1.0.0"

id = "exact_radius"
version = "1.9.2"
name = "Exact Radius"
tagline = "Make selected vertex rings exact-radius circles, many at once"
maintainer = "Patrick Tiefenbacher"
type = "add-on"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2026 Patrick Tiefenbacher",
]

tags = ["Mesh", "Modeling"]

website = "https://github.com/Matrex96/blender-exact-radius"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "*.blend1",
  "/docs/",
  "/tests/",
  "/.gitignore",
]
